import turtle
#turtle is the function in python to access the arrow where to move.
srn = turtle.Screen()
srn.title("Indian Flag")
turtle.speed(1)
srn.bgcolor("#121212")
turtle.pencolor("white")
turtle.penup()
turtle.goto(-100, 100)

turtle.fillcolor("#FF9933")
turtle.begin_fill()
turtle.setheading(90)
turtle.pendown()
turtle.forward(55)
turtle.setheading(0)
turtle.forward(300)
turtle.setheading(270)
turtle.forward(55)
turtle.setheading(180)
turtle.forward(300)
turtle.end_fill()

turtle.fillcolor("white")
turtle.begin_fill()
turtle.setheading(270)
turtle.forward(55)
turtle.setheading(0)
turtle.forward(300)
turtle.setheading(90)
turtle.forward(55)
turtle.end_fill()


turtle.penup()
turtle.setheading(180)
turtle.forward(160)
turtle.setheading(270)
turtle.pencolor("black")
turtle.forward(27.5)
turtle.pendown()

turtle.fillcolor("navy")
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

turtle.penup()
# turtle.backward(5)
turtle.setheading(180)
turtle.forward(15)
turtle.setheading(270)
# turtle.setheading(270)
# turtle.forward(15)
turtle.pendown()
turtle.pensize(2)
turtle.circle(20)

turtle.penup()
turtle.pencolor("navy")
turtle.setheading(0)
turtle.forward(19)
turtle.pendown()
turtle.pensize(0.1)
for i in range(24):
    turtle.forward(20)
    turtle.backward(20)
    turtle.left(15)


turtle.penup()
turtle.setheading(0)
turtle.forward(156.3)
turtle.setheading(270)
turtle.forward(27.5)
turtle.pendown()

turtle.fillcolor("#138808")
turtle.pencolor("white")
turtle.begin_fill()
turtle.forward(55)
turtle.setheading(180)
turtle.forward(300)
turtle.setheading(90)
turtle.forward(55)
turtle.end_fill()

# turtle.fillcolor("gray")
# turtle.begin_fill()
turtle.pensize(1)
turtle.setheading(90)
turtle.forward(140)
turtle.setheading(180)
turtle.forward(10)
turtle.setheading(270)
turtle.forward(500)
turtle.setheading(180)
turtle.forward(100)
turtle.setheading(270)
turtle.forward(50)
turtle.setheading(360)
turtle.forward(210)
turtle.setheading(90)
turtle.forward(50)
turtle.setheading(180)
turtle.forward(100)
turtle.setheading(90)
turtle.forward(310)
# turtle.end_fill()

turtle.penup()
turtle.goto(-120, 230)
turtle.pendown()
turtle.write("Happy Independence Day", move=True, font=("Varela Round",20))
turtle.hideturtle()

turtle.done()
